version: "3.7"
services:
  admin-server-service:
    image: openjdk:11
    volumes:
      - ./build/libs:/app
    ports:
      - "9090:9090"
#    environment:
#      JAVA_TOOL_OPTIONS: "
#        -Deureka.client.enabled=false
#      "
    command: java -jar /app/admin-server-0.0.1-SNAPSHOT.jar
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network